# Do not keep zsh sessions (.zsh_sessions directory).
# https://superuser.com/questions/1610587/disable-zsh-session-folder-completely
export SHELL_SESSIONS_DISABLE=1

# Use homebrew.
eval "$(/opt/homebrew/bin/brew shellenv)"
