# echo "[DEBUG] ~/.zshrc says SHELL=$SHELL"
#

export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/run/user/$UID}"

# Enable ls colors on macos
export CLICOLOR=1

export MY_JOBS=/lustre/isaac/scratch/jmill165/jobs

# https://zsh.sourceforge.io/Doc/Release/Prompt-Expansion.html
export PROMPT="[%n@%m] %1~ %# "

if command -v nvim &> /dev/null ; then
    echo "found nvim"
    alias vi=nvim
fi

# Created by newuser for 5.5.1
HISTFILE=~/.histfile
HISTSIZE=100000
SAVEHIST=1000000
setopt beep
setopt nomatch
setopt notify
setopt inc_append_history

unsetopt autocd
unsetopt extendedglob

bindkey -e

zstyle :compinstall filename '/nfs/home/jmill165/.zshrc'

# Tab Completion
# Every style defined here should be called after autoloading and calling compinit. 
# https://thevaluable.dev/zsh-completion-guide-examples/
autoload -Uz compinit
compinit

# Case insensitive autocomplete.
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'

# https://zsh.sourceforge.io/Doc/Release/Options.html#Completion-4
# On an ambiguous completion, instead of listing possibilities or beeping, insert the first match immediately. 
setopt menu_complete

unsetopt list_rows_first

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# User specific aliases and functions
if [ -f ~/.bash_aliases ]; then
	. ~/.bash_aliases
fi

if [ -f ~/.zsh_aliases ]; then
	. ~/.zsh_aliases
fi


# Show me if I have tmux sessions active
# echo "tmux: $(tmux ls)"

setopt SH_WORD_SPLIT

# Use directory stack
export DIRSTACKSIZE=9
setopt autopushd
setopt pushdminus
setopt pushdsilent
setopt pushdtohome


# Aliases
alias hist="history 0 | less"
# END
